//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using RosMessageGeneration;

namespace RosMessageTypes.RoboticsDemo
{
    public class ObjectPosSize : Message
    {
        public const string RosMessageName = "robotics_demo/ObjectPosSize";

        public float depth;
        public float width;
        public float height;
        public float mass;

        public ObjectPosSize()
        {
            this.depth = 0.0f;
            this.width = 0.0f;
            this.height = 0.0f;
            this.mass = 0.0f;
        }

        public ObjectPosSize(float depth, float width, float height, float mass)
        {
            this.depth = depth;
            this.width = width;
            this.height = height;
            this.mass = mass;
        }
        public override List<byte[]> SerializationStatements()
        {
            var listOfSerializations = new List<byte[]>();
            listOfSerializations.Add(BitConverter.GetBytes(this.depth));
            listOfSerializations.Add(BitConverter.GetBytes(this.width));
            listOfSerializations.Add(BitConverter.GetBytes(this.height));
            listOfSerializations.Add(BitConverter.GetBytes(this.mass));

            return listOfSerializations;
        }

        public override int Deserialize(byte[] data, int offset)
        {
            this.depth = BitConverter.ToSingle(data, offset);
            offset += 4;
            this.width = BitConverter.ToSingle(data, offset);
            offset += 4;
            this.height = BitConverter.ToSingle(data, offset);
            offset += 4;
            this.mass = BitConverter.ToSingle(data, offset);
            offset += 4;

            return offset;
        }

        public override string ToString()
        {
            return "ObjectPosSize: " +
            "\ndepth: " + depth.ToString() +
            "\nwidth: " + width.ToString() +
            "\nheight: " + height.ToString() +
            "\nmass: " + mass.ToString();
        }
    }
}
