//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using RosMessageGeneration;

namespace RosMessageTypes.RoboticsDemo
{
    public class QuadComm : Message
    {
        public const string RosMessageName = "robotics_demo/QuadComm";

        public float roll;
        public float pitch;
        public float yaw;
        public float h_vel;

        public QuadComm()
        {
            this.roll = 0.0f;
            this.pitch = 0.0f;
            this.yaw = 0.0f;
            this.h_vel = 0.0f;
        }

        public QuadComm(float roll, float pitch, float yaw, float h_vel)
        {
            this.roll = roll;
            this.pitch = pitch;
            this.yaw = yaw;
            this.h_vel = h_vel;
        }
        public override List<byte[]> SerializationStatements()
        {
            var listOfSerializations = new List<byte[]>();
            listOfSerializations.Add(BitConverter.GetBytes(this.roll));
            listOfSerializations.Add(BitConverter.GetBytes(this.pitch));
            listOfSerializations.Add(BitConverter.GetBytes(this.yaw));
            listOfSerializations.Add(BitConverter.GetBytes(this.h_vel));

            return listOfSerializations;
        }

        public override int Deserialize(byte[] data, int offset)
        {
            this.roll = BitConverter.ToSingle(data, offset);
            offset += 4;
            this.pitch = BitConverter.ToSingle(data, offset);
            offset += 4;
            this.yaw = BitConverter.ToSingle(data, offset);
            offset += 4;
            this.h_vel = BitConverter.ToSingle(data, offset);
            offset += 4;

            return offset;
        }

        public override string ToString()
        {
            return "QuadComm: " +
            "\nroll: " + roll.ToString() +
            "\npitch: " + pitch.ToString() +
            "\nyaw: " + yaw.ToString() +
            "\nh_vel: " + h_vel.ToString();
        }
    }
}
