//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using RosMessageGeneration;

namespace RosMessageTypes.RoboticsDemo
{
    public class QuadForce : Message
    {
        public const string RosMessageName = "robotics_demo/QuadForce";

        public float flm;
        public float frm;
        public float rlm;
        public float rrm;
        public float yaw;

        public QuadForce()
        {
            this.flm = 0.0f;
            this.frm = 0.0f;
            this.rlm = 0.0f;
            this.rrm = 0.0f;
            this.yaw = 0.0f;
        }

        public QuadForce(float flm, float frm, float rlm, float rrm, float yaw)
        {
            this.flm = flm;
            this.frm = frm;
            this.rlm = rlm;
            this.rrm = rrm;
            this.yaw = yaw;
        }
        public override List<byte[]> SerializationStatements()
        {
            var listOfSerializations = new List<byte[]>();
            listOfSerializations.Add(BitConverter.GetBytes(this.flm));
            listOfSerializations.Add(BitConverter.GetBytes(this.frm));
            listOfSerializations.Add(BitConverter.GetBytes(this.rlm));
            listOfSerializations.Add(BitConverter.GetBytes(this.rrm));
            listOfSerializations.Add(BitConverter.GetBytes(this.yaw));

            return listOfSerializations;
        }

        public override int Deserialize(byte[] data, int offset)
        {
            this.flm = BitConverter.ToSingle(data, offset);
            offset += 4;
            this.frm = BitConverter.ToSingle(data, offset);
            offset += 4;
            this.rlm = BitConverter.ToSingle(data, offset);
            offset += 4;
            this.rrm = BitConverter.ToSingle(data, offset);
            offset += 4;
            this.yaw = BitConverter.ToSingle(data, offset);
            offset += 4;

            return offset;
        }

        public override string ToString()
        {
            return "QuadForce: " +
            "\nflm: " + flm.ToString() +
            "\nfrm: " + frm.ToString() +
            "\nrlm: " + rlm.ToString() +
            "\nrrm: " + rrm.ToString() +
            "\nyaw: " + yaw.ToString();
        }
    }
}
